"""Generic sortable entity table."""
from __future__ import annotations

from dash import dash_table, html

from components.freshness_presentation import FRESHNESS_PRESENTATION
from services.monitoring_service import Freshness


def freshness_style_rules(column_id: str) -> list[dict]:
    """Colour a freshness column by semantic state, never by its label.

    Joins on the hidden `_state` key, whose values come from the `Freshness`
    enum. Two things this deliberately avoids: matching the rendered text
    ("Stale"), which would break the moment wording changes; and matching
    `_severity`, whose numbers exist to order rows and carry no visual meaning.

    Generated by iterating the enum, so a new state cannot ship unstyled. The
    colour token itself comes from `freshness_presentation`, the same table
    `freshness_badge` reads, so the two renderers cannot disagree on a state's
    colour.

    Text colour only — no background fill. Thirty tinted cells would put more
    colour on this screen than the whole Device page, and colour marks
    exceptions rather than filling a column.
    """
    return [
        {
            "if": {"filter_query": f'{{_state}} eq "{state.value}"',
                   "column_id": column_id},
            "color": f"var(--state-{FRESHNESS_PRESENTATION[state].text_token}-text)",
        }
        for state in Freshness
    ]


def entity_table(
    table_id: str,
    columns: list[dict],
    rows: list[dict],
    sort_by: str | None = None,
    link_column_id: str | None = None,
    state_column_id: str | None = None,
    administrative_state_column_id: str | None = None,
    responsive: bool = False,
    filter_action: str = "native",
    column_widths: dict[str, str] | None = None,
    markdown_link_target: str | None = None,
    extra_wrapper_class: str | None = None,
    extra_style_data_conditional: list[dict] | None = None,
) -> html.Div:
    """Render a sortable, filterable DataTable.

    columns: list of {"name": str, "id": str, ...} dicts.
    rows: list of row dicts. Rows may carry extra keys not listed in
        `columns` (e.g. an internal id) for a click callback to read via
        `active_cell` without rendering them as a column.
    link_column_id: column id styled to look clickable; a same-tab
        navigation callback (keyed off `active_cell`) is wired separately.
        Plain cell click-to-navigate is used instead of markdown links
        because dash_table hardcodes markdown-rendered links to
        target="_blank", which would break in-app navigation.
    state_column_id: column coloured by each row's hidden `_state` key.
        Rows must carry `_state`; see freshness_style_rules.
    administrative_state_column_id: identifies an administrative lifecycle
        column for presentation only. It is intentionally separate from
        `state_column_id`, which means monitoring freshness.
    column_widths: {column_id: css width} for columns that should not grow.
        dash_table hands slack to every column, so a wide table inflates
        "ku01" to 320px alongside the plant name it belongs to. Each entry
        pins width/minWidth/maxWidth together — `width` alone is only a
        suggestion. Leave the identity column out: whatever is unconstrained
        absorbs the slack, and that should be the longest value in the table.
    filter_action: DataTable's own filter row. "native" (the default) is
        right for a table that is its page's only filter surface. A page
        carrying its own toolbar passes "none" so the two do not stack —
        sorting is unaffected either way.
    responsive: opt this table into the shared narrow-screen record-card
        presentation. The underlying DataTable, data, filtering, paging and
        active-cell behaviour stay unchanged; CSS only changes how its rows
        are arranged below the responsive breakpoint.
    markdown_link_target: optional target for markdown links in this table.
        User Administration uses ``_self`` so its Edit affordance activates
        the existing cell callback without spawning a duplicate browser tab.
    extra_wrapper_class: optional additional modifier class on the wrapper,
        for table-scoped CSS (e.g. a column-level chip treatment).
    extra_style_data_conditional: optional per-row/cell style overrides
        appended after the built-in rules (e.g. rendering specific rows'
        link column as non-clickable plain text).
    """
    # Derived from the column spec rather than a per-page list: 900 < 1,000 <
    # 12,000 only reads correctly right-aligned, and the columns that need it
    # already declare `type: "numeric"` so native sorting works. One
    # declaration, two behaviours.
    numeric_ids = [c["id"] for c in columns if c.get("type") == "numeric"]
    numeric_alignment = [
        {"if": {"column_id": cid}, "textAlign": "right"} for cid in numeric_ids
    ]
    style_cell_conditional = numeric_alignment + (
        [
            {
                "if": {"column_id": link_column_id},
                # Token, not a hex literal: this is --color-accent, and an
                # accent change must not leave this link blue behind.
                "color": "var(--color-accent)",
                "textDecoration": "underline",
                "cursor": "pointer",
                # The identity column wraps instead of truncating. Every other
                # column gets an ellipsis (see app.css), but half of "Itaipu
                # Binacional Dam (Paraguay part)" is not an identity, and this
                # is the cell the operator clicks to navigate.
                "whiteSpace": "normal",
                "overflowWrap": "anywhere",
            }
        ]
        if link_column_id
        else []
    )
    style_cell_conditional += [
        {
            "if": {"column_id": column_id},
            "width": width,
            "minWidth": width,
            "maxWidth": width,
        }
        for column_id, width in (column_widths or {}).items()
    ]
    wrapper_classes = ["entity-table-wrapper"]
    if responsive:
        wrapper_classes.append("entity-table-wrapper--responsive")
    if state_column_id:
        wrapper_classes.append("entity-table-wrapper--freshness-axis")
    if administrative_state_column_id:
        wrapper_classes.append("entity-table-wrapper--administrative-axis")
    if extra_wrapper_class:
        wrapper_classes.append(extra_wrapper_class)

    return html.Div(
        className=" ".join(wrapper_classes),
        children=[
            dash_table.DataTable(
                id=table_id,
                columns=columns,
                data=rows,
                sort_action="native",
                filter_action=filter_action,
                page_size=30,
                style_as_list_view=True,
                style_table={"overflowX": "auto"},
                # OBS-2: dash_table's stylesheet sets `text-overflow: inherit`
                # on the inner .dash-cell-value with a 4-class selector, so the
                # value must be set on the `td` here — an app.css rule targeting
                # the inner div loses the cascade and silently does nothing.
                # Verified against computed style, not the stylesheet source.
                style_cell={
                    "textAlign": "left",
                    # ~40 px rows against a 40-44 px target. A target, not a
                    # guarantee: rows whose plant name wraps are taller by
                    # design, which is the correct trade for never hiding an
                    # identity.
                    "padding": "11px 12px",
                    "overflow": "hidden",
                    "textOverflow": "ellipsis",
                },
                # A label for the column, not another row of data. It
                # previously carried `#f9fafb` — the same fill as the odd-row
                # stripe below — so with `style_as_list_view` removing
                # vertical borders too, nothing separated the names from the
                # values. White ground and a firm bottom rule do that job
                # without adding a third surface colour. The extra right
                # padding is room for dash_table's sort arrow, which sat
                # flush against the label and read as "⇅Device".
                style_header={
                    "backgroundColor": "var(--color-surface)",
                    "borderBottom": "2px solid #cbd2d9",
                    # The heading of the table, not a caption for it. An
                    # 11px muted label disappeared against the data it was
                    # supposed to introduce; it now sits a step above the
                    # 13px cells in colour and weight rather than below them
                    # in size.
                    "color": "var(--color-text)",
                    "fontSize": "13px",
                    "fontWeight": "600",
                    "letterSpacing": "0.05em",
                    "textTransform": "uppercase",
                    "paddingRight": "22px",
                    "paddingLeft": "12px",
                },
                markdown_options=(
                    {"link_target": markdown_link_target}
                    if markdown_link_target else None
                ),
                style_header_conditional=[
                    {"if": {"column_id": cid}, "textAlign": "right"}
                    for cid in numeric_ids
                ],
                # No zebra striping: `style_as_list_view` above already draws
                # a rule between rows, and two separation systems on one table
                # read as noise rather than as structure.
                style_data_conditional=[
                    *(freshness_style_rules(state_column_id)
                      if state_column_id else []),
                    *(extra_style_data_conditional or []),
                ],
                style_cell_conditional=style_cell_conditional,
            )
        ],
    )
